# -*- coding: utf-8 -*-
"""week3_assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyAhz2ApvS6t7gUUijpCN-RlLD1GXcJM
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
# %matplotlib inline

#PART A: Understanding the Dataset
#Q1 Dataset Overview

#Laoding the dataset
df=pd.read_csv('data5.csv')

#Number of rows and columns present
print("Shape:",df.shape)
print("No. of rows:",df.shape[0])
print("No. of columns:",df.shape[1])

#Names of all columns
print('\n Column Names:')
print(df.columns)

#First 10 records
print(df.head(10))

#Q2 Data Types and Missing Values

#Data type of each column
print('\nDatatype of Columns:')
print(df.dtypes)

#Missing Values
print('\nMissing Values:')
print(round(df.isnull().sum()))

#No Missing values exist

#Q3 Descriptive Statistics
print(df.describe())

''' From generated summary statistics we get the following results:
"rainfall_mm" has the highest mean value equal to 754.054667.
"rainfall_mm" has the highest standard devation equal to 255.097216.'''

#PARt B: Exploratory Data Analysis(EDA)
#Q4 Distribution Analysis

px.histogram(df,x='rainfall_mm',title='Distribution of Rainfall')

'''The most common rainfall amount occurs in the range of 800-850mm,with a count of 101.
The majority of data lies between 400mm and 1150mmand there is a sharp decline in frequency at the extremes which means that very low rainfall and very high rainfall are less common.'''

px.histogram(df,x='temperature_c',title="Distribution of Temperature")

'''The data shows a relatively flat distribution between 19 and 37°C.
The highest concentration of data points occurs around 22-23°C where the frequency reaches at nearly 90.
There is a sharp decline in frequency at the extremes which means that very low temperatures and very high temperatures are less common.'''

px.histogram(df,x='fertilizer_kg',title="Distribution of Fertilizer")

'''The highest frequency occurs between 75 and 85kg,where the count reaches its maximum of 100.There is another notable spike near the 190 kg mark.
The counts for fertilizer amounts below 60 kg and above 240 kg are the lowest on the graph, indicating these extreme amounts are less common.'''

px.histogram(df,x="yield_ton_per_hectare",title="Yield ton per hectare")

'''The graph shows a roughly symmetrical distribtuion,while there is a dip near the 5.3 mark.
The majority of data points are concentrated between 4 and 6 tons per hectare.'''

#Q5 Crop Type Analysis
print("Number of records for each crop type:")
crop_count=df.crop_type.value_counts()
print(crop_count)

#count plot
px.bar(df,x=crop_count.index,y=crop_count.values,labels={"x":"Crop Type","y":"Count"},title="Count of each crop type")


#"Cotton" appears most frequently.

#Soil Type Analysis
print("Number of records for each soil type:")
soil_count=df.soil_type.value_counts()
print(soil_count)

#count plot
px.bar(df,x=soil_count.index,y=soil_count.values,labels={"x":"Soil Type","y":"Count"},title="Count of each soil type")

#"Clay Soil" is the most common type of soil.

#Q7 Yield Distribution
px.histogram(df,x='yield_ton_per_hectare',title='Yield Distribution')

"""The Yield distriubtion is approximately normal, with most crop yields concentrated around 5 tons per hectare.
The histogram shows a bell shaped patten with no significant skewness, hence no obvious outliers are observed.
This indicates that there are no unusually high or low values that could significantly affect the analysis."""

#Q8 Scatter Plot Analysis
plt.title('Rainfall vs Yield')
sns.scatterplot(data=df,x='rainfall_mm',y='yield_ton_per_hectare',alpha=0.7,s=15);

plt.title('Fertilizer vs Yield')
sns.scatterplot(data=df,x='fertilizer_kg',y='yield_ton_per_hectare',alpha=0.7,s=15);

''' Rainfall appears to have a stronger relationship with yield than fertilizer usage. The Rainfall vs Yield scatter plot shows a clear positive trend, whereas the fertilizer vs yield scatter plot is more dispersed and shows a weaker pattern.
The plot "Rainfall vs Yield" indicates that yield generally increases as rainfall increases.'''

#Q9 Correlation Analysis

le = LabelEncoder()
df['crop_type'] = le.fit_transform(df['crop_type'])
df['soil_type'] = le.fit_transform(df['soil_type'])

corr_matrix=df.corr()
print(corr_matrix)

#Heatmap
sns.heatmap(corr_matrix,cmap='Reds',annot=True)
plt.title('Correlation Matrix')

'''The top three features most correlated with crop yield:
(i) Rainfall (rainfall_mm)(0.55)
(ii) Irrigation (irrigation_hours)(0.54)
(iii) Fertilizer (fertilizer_kg))(0.28)'''

#Q 10 Group-Based Analysis
#Average yield for each crop type

print(df.crop_type.value_counts())
crop_yield=df.groupby('crop_type')['yield_ton_per_hectare'].mean()
print('\nAverage Yield',crop_yield)

#Average yield for each soil type
print('\n',df.soil_type.value_counts())
soil_yield=df.groupby('soil_type')['yield_ton_per_hectare'].mean()
print('\nAverage Yield',soil_yield)

'''crop type 2 and soil type 1 have the highest average yield.'''

#PART C Data Preparation
#Q11 Feature Encoding
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)
df_encoded = pd.get_dummies (df, columns=categorical_cols, drop_first=False)
for col in df_encoded.columns:
  if df_encoded [col].dtype == bool:
     df_encoded [col] = df_encoded [col].astype(int)
print(df_encoded.head(5))

#Q12 Feature Selection
x=df.drop(['yield_ton_per_hectare'],axis=1)
y=df['yield_ton_per_hectare']

'''yield_ton_per_hectare is being used as the target variable.'''

#PART D: Machine Learning
#Q13 Train-Test Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("Shape of:")
print("x_train",x_train.shape)
print("x_testn",x_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

#Q14 Linear Regression Model
lr=LinearRegression()
lr.fit(x_train,y_train)

#Model coefficients and intercept
print(x.columns)
print("Coefficients:",lr.coef_)
print("Intercept:",lr.intercept_)

'''"irrigation_hours" has the highest positive coefficient.'''